// Generates assets-bundle.js: the web UI embedded as base64 so it survives
// packaging. `pkg` only bundles files it can trace through require(); its
// pkg.assets mechanism never picked up public/ for this project, which left
// every packaged exe without a web UI. Run automatically by npm run build:all.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const sources = [
  // launcher.html now lives in public/ and is picked up by the walk below.
];

function walk(dir, rel) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    const relPath = rel ? `${rel}/${entry.name}` : entry.name;
    if (entry.isDirectory()) walk(abs, relPath);
    else sources.push({ from: abs, to: `public/${relPath}` });
  }
}
walk(path.join(root, 'public'), '');

const files = {};
let total = 0;
for (const src of sources) {
  if (!fs.existsSync(src.from)) {
    console.warn(`[bundle] missing source, skipped: ${src.to}`);
    continue;
  }
  const buf = fs.readFileSync(src.from);
  total += buf.length;
  files[src.to] = buf.toString('base64');
}

const crypto = require('crypto');
// Content hash: data/web is refreshed whenever the UI changes, not only when
// the version number is bumped (same-version rebuilds kept serving stale files).
const hash = crypto.createHash('sha256').update(JSON.stringify(files)).digest('hex').slice(0, 16);
const version = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;
const out = `// AUTO-GENERATED by build-assets.js - do not edit by hand.
// Embedded web UI for packaged builds (pkg cannot embed these as assets).
// Source version: ${version}  Files: ${Object.keys(files).length}
'use strict';

const VERSION = ${JSON.stringify(version)};
const HASH = ${JSON.stringify(hash)};
const FILES = {
${Object.keys(files).sort().map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(files[k])}`).join(',\n')}
};

module.exports = { VERSION, HASH, FILES };
`;

fs.writeFileSync(path.join(root, 'src', 'assets-bundle.js'), out, 'utf8');
console.log(`[bundle] assets-bundle.js written: ${Object.keys(files).length} files, ${(total / 1024).toFixed(0)} KB raw, ${(out.length / 1024 / 1024).toFixed(2)} MB embedded (v${version})`);
